/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;



import java.sql.Connection;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import conexion.Conexion;
import controlador.ControladorHorario;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import modelo.Grupo;
import modelo.Horario;
import modelo.Materia;
import modelo.Profesor;

/**
 *
 * @author Itzel_CG
 */
public class VistaRegistroHorario extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistroUsuario
     */
   
    private DefaultTableModel modeloTabla;
    private List<JComboBox<String>> comboBoxesM;
    private List<JComboBox<String>> comboBoxes;
 
    public VistaRegistroHorario() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Registro Horario- SISTEMA DE LA INSTITUCIÓN");
        this.setSize(new Dimension (1100, 550));
        cargarGrupos();
        
        
        
        comboBoxesM = new ArrayList<>();
    
        comboBoxesM.add(ComboMateria1);
        comboBoxesM.add(ComboMateria2);
        comboBoxesM.add(ComboMateria3);
        comboBoxesM.add(ComboMateria4);
        comboBoxesM.add(ComboMateria5);
        
        comboBoxesM.add(ComboMateria1M);
        comboBoxesM.add(ComboMateria2M);
        comboBoxesM.add(ComboMateria3M);
        comboBoxesM.add(ComboMateria4M);
        comboBoxesM.add(ComboMateria5M);
        
        comboBoxesM.add(ComboMateria1Mi);
        comboBoxesM.add(ComboMateria2Mi);
        comboBoxesM.add(ComboMateria3Mi);
        comboBoxesM.add(ComboMateria4Mi);
        comboBoxesM.add(ComboMateria5Mi);
        
        comboBoxesM.add(ComboMateria1J);
        comboBoxesM.add(ComboMateria2J);
        comboBoxesM.add(ComboMateria3J);
        comboBoxesM.add(ComboMateria4J);
        comboBoxesM.add(ComboMateria5J);
        
        comboBoxesM.add(ComboMateria1V);
        comboBoxesM.add(ComboMateria2V);
        comboBoxesM.add(ComboMateria3V);
        comboBoxesM.add(ComboMateria4V);
        comboBoxesM.add(ComboMateria5V);
        
       cargarMaterias();
       
       
       
        comboBoxes = new ArrayList<>();
    
        comboBoxes.add(ComboProfesor1);
        comboBoxes.add(ComboProfesor2);
        comboBoxes.add(ComboProfesor3);
        comboBoxes.add(ComboProfesor4);
        comboBoxes.add(ComboProfesor5);
        
        comboBoxes.add(ComboProfesor1M);
        comboBoxes.add(ComboProfesor2M);
        comboBoxes.add(ComboProfesor3M);
        comboBoxes.add(ComboProfesor4M);
        comboBoxes.add(ComboProfesor5M);
       
        comboBoxes.add(ComboProfesor1Mi);
        comboBoxes.add(ComboProfesor2Mi);
        comboBoxes.add(ComboProfesor3Mi);
        comboBoxes.add(ComboProfesor4Mi);
        comboBoxes.add(ComboProfesor5Mi);
        
        comboBoxes.add(ComboProfesor1J);
        comboBoxes.add(ComboProfesor2J);
        comboBoxes.add(ComboProfesor3J);
        comboBoxes.add(ComboProfesor4J);
        comboBoxes.add(ComboProfesor5J);
        
        comboBoxes.add(ComboProfesor1V);
        comboBoxes.add(ComboProfesor2V);
        comboBoxes.add(ComboProfesor3V);
        comboBoxes.add(ComboProfesor4V);
        comboBoxes.add(ComboProfesor5V);
       
       cargarProfesores();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVentanaAnterior = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnVentanaAnterior1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        msg5 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        comboGrupo = new javax.swing.JComboBox<>();
        panelHorario = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ComboMateria1 = new javax.swing.JComboBox<>();
        ComboProfesor1 = new javax.swing.JComboBox<>();
        ComboMateria1M = new javax.swing.JComboBox<>();
        ComboProfesor1M = new javax.swing.JComboBox<>();
        ComboMateria1Mi = new javax.swing.JComboBox<>();
        ComboProfesor1Mi = new javax.swing.JComboBox<>();
        ComboMateria1J = new javax.swing.JComboBox<>();
        ComboProfesor1J = new javax.swing.JComboBox<>();
        ComboMateria1V = new javax.swing.JComboBox<>();
        ComboProfesor1V = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        ComboMateria2 = new javax.swing.JComboBox<>();
        ComboProfesor2 = new javax.swing.JComboBox<>();
        ComboMateria2M = new javax.swing.JComboBox<>();
        ComboProfesor2M = new javax.swing.JComboBox<>();
        ComboMateria2Mi = new javax.swing.JComboBox<>();
        ComboProfesor2Mi = new javax.swing.JComboBox<>();
        ComboMateria2J = new javax.swing.JComboBox<>();
        ComboProfesor2J = new javax.swing.JComboBox<>();
        ComboMateria2V = new javax.swing.JComboBox<>();
        ComboProfesor2V = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ComboMateria3 = new javax.swing.JComboBox<>();
        ComboProfesor3 = new javax.swing.JComboBox<>();
        ComboMateria3M = new javax.swing.JComboBox<>();
        ComboProfesor3M = new javax.swing.JComboBox<>();
        ComboMateria3Mi = new javax.swing.JComboBox<>();
        ComboProfesor3Mi = new javax.swing.JComboBox<>();
        ComboMateria3J = new javax.swing.JComboBox<>();
        ComboProfesor3J = new javax.swing.JComboBox<>();
        ComboMateria3V = new javax.swing.JComboBox<>();
        ComboProfesor3V = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ComboMateria4 = new javax.swing.JComboBox<>();
        ComboProfesor4 = new javax.swing.JComboBox<>();
        ComboMateria4M = new javax.swing.JComboBox<>();
        ComboProfesor4M = new javax.swing.JComboBox<>();
        ComboMateria4Mi = new javax.swing.JComboBox<>();
        ComboProfesor4Mi = new javax.swing.JComboBox<>();
        ComboMateria4J = new javax.swing.JComboBox<>();
        ComboProfesor4J = new javax.swing.JComboBox<>();
        ComboMateria4V = new javax.swing.JComboBox<>();
        ComboProfesor4V = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        ComboMateria5 = new javax.swing.JComboBox<>();
        ComboProfesor5 = new javax.swing.JComboBox<>();
        ComboMateria5M = new javax.swing.JComboBox<>();
        ComboProfesor5M = new javax.swing.JComboBox<>();
        ComboMateria5Mi = new javax.swing.JComboBox<>();
        ComboProfesor5Mi = new javax.swing.JComboBox<>();
        ComboMateria5J = new javax.swing.JComboBox<>();
        ComboProfesor5J = new javax.swing.JComboBox<>();
        ComboMateria5V = new javax.swing.JComboBox<>();
        ComboProfesor5V = new javax.swing.JComboBox<>();

        btnVentanaAnterior.setFont(new java.awt.Font("Ebrima", 1, 13)); // NOI18N
        btnVentanaAnterior.setForeground(new java.awt.Color(255, 255, 255));
        btnVentanaAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anterior.png"))); // NOI18N
        btnVentanaAnterior.setText("Ventana anterior");
        btnVentanaAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentanaAnteriorMouseClicked(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel26.setText("Nombre de la asignatura:");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Vector.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(1, 25, 71));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(1, 25, 71));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Horario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 30));

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(350, 600));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 148, -1, 223));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/i6.1.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 150, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Ebrima", 1, 32)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("EscuelaConnect ");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        btnVentanaAnterior1.setFont(new java.awt.Font("Ebrima", 1, 13)); // NOI18N
        btnVentanaAnterior1.setForeground(new java.awt.Color(255, 255, 255));
        btnVentanaAnterior1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anterior.png"))); // NOI18N
        btnVentanaAnterior1.setText("Ventana anterior");
        btnVentanaAnterior1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentanaAnterior1MouseClicked(evt);
            }
        });
        jPanel3.add(btnVentanaAnterior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 240, 460));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(0, 51, 102));
        jLabel13.setFont(new java.awt.Font("Ebrima", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 102));
        jLabel13.setText("Nuevo Horario");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        msg5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        msg5.setForeground(new java.awt.Color(255, 0, 0));
        msg5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel4.add(msg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel28.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel28.setText("GRUPO:");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 90, 26));

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar-el-archivo.png"))); // NOI18N
        btnGuardar.setText("Guardar PDF");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel4.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 160, 40));

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/archivo.png"))); // NOI18N
        btnAgregar.setText("Agregar Horario");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel4.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, 40));

        comboGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(comboGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 120, 30));

        panelHorario.setBackground(new java.awt.Color(153, 204, 255));
        panelHorario.setLayout(new java.awt.GridLayout(7, 12));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Hora");
        panelHorario.add(jLabel25);

        jLabel38.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("LUNES");
        panelHorario.add(jLabel38);

        jLabel39.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("          ");
        panelHorario.add(jLabel39);

        jLabel40.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("MARTES");
        panelHorario.add(jLabel40);

        jLabel41.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("        ");
        panelHorario.add(jLabel41);

        jLabel42.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("MIERCOLES");
        panelHorario.add(jLabel42);

        jLabel43.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("     ");
        panelHorario.add(jLabel43);

        jLabel44.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("JUEVES");
        panelHorario.add(jLabel44);

        jLabel45.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelHorario.add(jLabel45);

        jLabel46.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("VIERNES");
        panelHorario.add(jLabel46);

        jLabel47.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelHorario.add(jLabel47);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("7:20-8:20");
        panelHorario.add(jLabel5);

        ComboMateria1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboMateria1.setBorder(null);
        panelHorario.add(ComboMateria1);

        ComboProfesor1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboProfesor1);

        ComboMateria1M.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria1M.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboMateria1M);

        ComboProfesor1M.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor1M.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboProfesor1M);

        ComboMateria1Mi.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria1Mi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboMateria1Mi);

        ComboProfesor1Mi.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor1Mi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboProfesor1Mi);

        ComboMateria1J.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria1J.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboMateria1J.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboMateria1JActionPerformed(evt);
            }
        });
        panelHorario.add(ComboMateria1J);

        ComboProfesor1J.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor1J.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboProfesor1J.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboProfesor1JActionPerformed(evt);
            }
        });
        panelHorario.add(ComboProfesor1J);

        ComboMateria1V.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria1V.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboMateria1V);

        ComboProfesor1V.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor1V.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboProfesor1V);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("8:20-9:20");
        panelHorario.add(jLabel8);

        ComboMateria2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboMateria2);

        ComboProfesor2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboProfesor2);

        ComboMateria2M.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria2M.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboMateria2M);

        ComboProfesor2M.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor2M.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboProfesor2M);

        ComboMateria2Mi.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria2Mi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboMateria2Mi);

        ComboProfesor2Mi.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor2Mi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboProfesor2Mi);

        ComboMateria2J.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria2J.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboMateria2J);

        ComboProfesor2J.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor2J.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboProfesor2J);

        ComboMateria2V.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria2V.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboMateria2V);

        ComboProfesor2V.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor2V.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboProfesor2V);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("9:20-10:00");
        panelHorario.add(jLabel6);

        jLabel48.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelHorario.add(jLabel48);

        jLabel49.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelHorario.add(jLabel49);

        jLabel50.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelHorario.add(jLabel50);

        jLabel51.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelHorario.add(jLabel51);

        jLabel52.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelHorario.add(jLabel52);

        jLabel53.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelHorario.add(jLabel53);

        jLabel54.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelHorario.add(jLabel54);

        jLabel55.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelHorario.add(jLabel55);

        jLabel56.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelHorario.add(jLabel56);

        jLabel57.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelHorario.add(jLabel57);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("10:00-11:00");
        panelHorario.add(jLabel7);

        ComboMateria3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboMateria3);

        ComboProfesor3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboProfesor3);

        ComboMateria3M.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria3M.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboMateria3M);

        ComboProfesor3M.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor3M.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboProfesor3M);

        ComboMateria3Mi.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria3Mi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboMateria3Mi);

        ComboProfesor3Mi.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor3Mi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboProfesor3Mi);

        ComboMateria3J.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria3J.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboMateria3J);

        ComboProfesor3J.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor3J.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboProfesor3J);

        ComboMateria3V.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria3V.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboMateria3V);

        ComboProfesor3V.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor3V.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboProfesor3V);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("11:00-12:00");
        panelHorario.add(jLabel4);

        ComboMateria4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboMateria4);

        ComboProfesor4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboProfesor4);

        ComboMateria4M.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria4M.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboMateria4M);

        ComboProfesor4M.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor4M.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboProfesor4M);

        ComboMateria4Mi.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria4Mi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboMateria4Mi);

        ComboProfesor4Mi.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor4Mi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboProfesor4Mi);

        ComboMateria4J.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria4J.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboMateria4J);

        ComboProfesor4J.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor4J.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboProfesor4J);

        ComboMateria4V.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria4V.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboMateria4V);

        ComboProfesor4V.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor4V.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboProfesor4V);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("12:00-13:00");
        panelHorario.add(jLabel9);

        ComboMateria5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboMateria5);

        ComboProfesor5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboProfesor5);

        ComboMateria5M.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria5M.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboMateria5M);

        ComboProfesor5M.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor5M.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboProfesor5M);

        ComboMateria5Mi.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria5Mi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboMateria5Mi);

        ComboProfesor5Mi.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor5Mi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboProfesor5Mi);

        ComboMateria5J.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria5J.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboMateria5J);

        ComboProfesor5J.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor5J.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboProfesor5J);

        ComboMateria5V.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboMateria5V.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboMateria5V);

        ComboProfesor5V.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ComboProfesor5V.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelHorario.add(ComboProfesor5V);

        jPanel4.add(panelHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 820, 290));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 840, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1096, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentanaAnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentanaAnteriorMouseClicked
      

    }//GEN-LAST:event_btnVentanaAnteriorMouseClicked

    private void btnVentanaAnterior1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentanaAnterior1MouseClicked
        VistaPrincipalP VistaPrincipalP = new VistaPrincipalP();
        VistaPrincipalP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentanaAnterior1MouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
      //agregarHorario();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
         //guardarHorario();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void ComboMateria1JActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboMateria1JActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboMateria1JActionPerformed

    private void ComboProfesor1JActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboProfesor1JActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboProfesor1JActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistroHorario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboMateria1;
    private javax.swing.JComboBox<String> ComboMateria1J;
    private javax.swing.JComboBox<String> ComboMateria1M;
    private javax.swing.JComboBox<String> ComboMateria1Mi;
    private javax.swing.JComboBox<String> ComboMateria1V;
    private javax.swing.JComboBox<String> ComboMateria2;
    private javax.swing.JComboBox<String> ComboMateria2J;
    private javax.swing.JComboBox<String> ComboMateria2M;
    private javax.swing.JComboBox<String> ComboMateria2Mi;
    private javax.swing.JComboBox<String> ComboMateria2V;
    private javax.swing.JComboBox<String> ComboMateria3;
    private javax.swing.JComboBox<String> ComboMateria3J;
    private javax.swing.JComboBox<String> ComboMateria3M;
    private javax.swing.JComboBox<String> ComboMateria3Mi;
    private javax.swing.JComboBox<String> ComboMateria3V;
    private javax.swing.JComboBox<String> ComboMateria4;
    private javax.swing.JComboBox<String> ComboMateria4J;
    private javax.swing.JComboBox<String> ComboMateria4M;
    private javax.swing.JComboBox<String> ComboMateria4Mi;
    private javax.swing.JComboBox<String> ComboMateria4V;
    private javax.swing.JComboBox<String> ComboMateria5;
    private javax.swing.JComboBox<String> ComboMateria5J;
    private javax.swing.JComboBox<String> ComboMateria5M;
    private javax.swing.JComboBox<String> ComboMateria5Mi;
    private javax.swing.JComboBox<String> ComboMateria5V;
    private javax.swing.JComboBox<String> ComboProfesor1;
    private javax.swing.JComboBox<String> ComboProfesor1J;
    private javax.swing.JComboBox<String> ComboProfesor1M;
    private javax.swing.JComboBox<String> ComboProfesor1Mi;
    private javax.swing.JComboBox<String> ComboProfesor1V;
    private javax.swing.JComboBox<String> ComboProfesor2;
    private javax.swing.JComboBox<String> ComboProfesor2J;
    private javax.swing.JComboBox<String> ComboProfesor2M;
    private javax.swing.JComboBox<String> ComboProfesor2Mi;
    private javax.swing.JComboBox<String> ComboProfesor2V;
    private javax.swing.JComboBox<String> ComboProfesor3;
    private javax.swing.JComboBox<String> ComboProfesor3J;
    private javax.swing.JComboBox<String> ComboProfesor3M;
    private javax.swing.JComboBox<String> ComboProfesor3Mi;
    private javax.swing.JComboBox<String> ComboProfesor3V;
    private javax.swing.JComboBox<String> ComboProfesor4;
    private javax.swing.JComboBox<String> ComboProfesor4J;
    private javax.swing.JComboBox<String> ComboProfesor4M;
    private javax.swing.JComboBox<String> ComboProfesor4Mi;
    private javax.swing.JComboBox<String> ComboProfesor4V;
    private javax.swing.JComboBox<String> ComboProfesor5;
    private javax.swing.JComboBox<String> ComboProfesor5J;
    private javax.swing.JComboBox<String> ComboProfesor5M;
    private javax.swing.JComboBox<String> ComboProfesor5Mi;
    private javax.swing.JComboBox<String> ComboProfesor5V;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel btnVentanaAnterior;
    private javax.swing.JLabel btnVentanaAnterior1;
    private javax.swing.JComboBox<String> comboGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel msg5;
    private javax.swing.JPanel panelHorario;
    // End of variables declaration//GEN-END:variables

    
    private void cargarGrupos() {
    Connection cn = null;
    Statement statement = null;
    ResultSet resultSet = null;

    try {
       
        cn = Conexion.conectar();
        statement = cn.createStatement();
        resultSet = statement.executeQuery("SELECT * FROM grupo");

        comboGrupo.removeAllItems();

        while (resultSet.next()) {
            String IdGrupo = resultSet.getString("IdGrupo");
            int IdCurso = resultSet.getInt("IdCurso");
            comboGrupo.addItem(new Grupo(IdGrupo, IdCurso).toString());
        }
        //System.out.println("Grupos cargados exitosamente");
    } catch (SQLException e) {
        e.printStackTrace();
    } finally {
     
        try {
            if (resultSet != null) resultSet.close();
            if (statement != null) statement.close();
            if (cn != null) cn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
    


    
    public void cargarMaterias() {
        Connection cn = null;
        Statement statement = null;
        ResultSet resultSet = null;

        try {
            cn = Conexion.conectar();
            statement = cn.createStatement();
            resultSet = statement.executeQuery("SELECT * FROM materia");

            // Elimina todos los elementos de los JComboBox
            for (JComboBox<String> comboBox : comboBoxesM) {
                comboBox.removeAllItems();
            }

            while (resultSet.next()) {
                String IdMateria = resultSet.getString("IdMateria");
                
                int IdCurso = resultSet.getInt("IdCurso");
                String materia = new Materia(IdMateria, IdCurso).toString();

                // Agrega la materia a cada JComboBox
                for (JComboBox<String> comboBox : comboBoxesM) {
                    comboBox.addItem(materia);
                }
            }
            //System.out.println("Materias cargadas exitosamente");
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                if (resultSet != null) resultSet.close();
                if (statement != null) statement.close();
                if (cn != null) cn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    
    
    
    
    
        public void cargarProfesores() {
        Connection cn = null;
        Statement statement = null;
        ResultSet resultSet = null;

        try {
            cn = Conexion.conectar();
            statement = cn.createStatement();
            resultSet = statement.executeQuery("SELECT * FROM tb_profesor");

            // Elimina todos los elementos de los JComboBox
            for (JComboBox<String> comboBox : comboBoxes) {
                comboBox.removeAllItems();
            }

            while (resultSet.next()) {
                int idProfesor = resultSet.getInt("IdProfesor");
                String nombre = resultSet.getString("nombre");
                String apellidoP = resultSet.getString("apellidoP");
                String apellidoM = resultSet.getString("apellidoM");
                String direccion = resultSet.getString("direccion");
                String telefono = resultSet.getString("telefono");
                String especialidad = resultSet.getString("especialidad");
                String cedula = resultSet.getString("cedula");
                int IdUsuario = resultSet.getInt("IdUsuario");
                
                String profesor = new Profesor(idProfesor, nombre, apellidoP, apellidoM, direccion, telefono, especialidad, cedula, IdUsuario).toString();

                // Agrega el profesor a cada JComboBox
                for (JComboBox<String> comboBox : comboBoxes) {
                    comboBox.addItem(profesor);
                }
            }
           // System.out.println("Profesores cargados exitosamente");
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                if (resultSet != null) resultSet.close();
                if (statement != null) statement.close();
                if (cn != null) cn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        }
 
    
}

    
    
    
    
    
    
    
    
    
    
    

    
    
    
   
    
    
    
    
    


