/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Validaciones.validacion;
import conexion.Conexion;
import controlador.ControladorAlumno;
import controlador.ControladorUsuario;
import java.awt.Color;
import static java.awt.Color.RED;
import java.awt.Dimension;
import modelo.Usuario;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Alumno;

//import java.sql.Statement;

/**
 *
 * @author Itzel_CG
 */



public class VistaModificarUsuario1 extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistroUsuario
     */
    private validacion validador;
    private boolean contraseñaVisible = false;
     
     
    public VistaModificarUsuario1() throws Exception {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Registro Usuario- SISTEMA DE LA INSTITUCIÓN");
        this.setSize(new Dimension (900, 550));
        validador = new validacion();
        
        cargarDatos();
        
    label1.setVisible(false);
    label2.setVisible(false);
    etiNombre1.setVisible(false);
    etiNombre2.setVisible(false);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVentanaAnterior = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnVentanaAnterior1 = new javax.swing.JLabel();
        etiNombre = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        etiNombre1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        msg5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ComboTipo = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        txtIdentificacion = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        lbOjo = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        etiNombre2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        btnVentanaAnterior.setFont(new java.awt.Font("Ebrima", 1, 13)); // NOI18N
        btnVentanaAnterior.setForeground(new java.awt.Color(255, 255, 255));
        btnVentanaAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anterior.png"))); // NOI18N
        btnVentanaAnterior.setText("Ventana anterior");
        btnVentanaAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentanaAnteriorMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(1, 25, 71));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(1, 25, 71));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 30));

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(350, 600));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 148, -1, 223));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/i6.1.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Ebrima", 1, 32)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("EscuelaConnect ");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        btnVentanaAnterior1.setFont(new java.awt.Font("Ebrima", 1, 13)); // NOI18N
        btnVentanaAnterior1.setForeground(new java.awt.Color(255, 255, 255));
        btnVentanaAnterior1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anterior.png"))); // NOI18N
        btnVentanaAnterior1.setText("Ventana anterior");
        btnVentanaAnterior1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentanaAnterior1MouseClicked(evt);
            }
        });
        jPanel3.add(btnVentanaAnterior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        etiNombre.setForeground(new java.awt.Color(255, 0, 0));
        etiNombre.setText("Solo letras");
        jPanel3.add(etiNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 60, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 270, 460));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiNombre1.setForeground(new java.awt.Color(255, 0, 0));
        etiNombre1.setText("Solo letras");
        jPanel4.add(etiNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 60, 30));

        jLabel13.setBackground(new java.awt.Color(0, 51, 102));
        jLabel13.setFont(new java.awt.Font("Ebrima", 1, 26)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 102));
        jLabel13.setText("Nuevo Usuario");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtNombre.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel4.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 220, -1));

        txtApellidos.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtApellidos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });
        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });
        jPanel4.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 220, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Apellidos");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 110, 26));

        msg5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        msg5.setForeground(new java.awt.Color(255, 0, 0));
        msg5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel4.add(msg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("Nombres");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 73, 26));

        txtUsuario.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        jPanel4.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 220, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel16.setText("Tipo de usuario");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 130, 26));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel20.setText("Contraseña");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 110, 26));

        txtCorreo.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtCorreo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCorreoMouseClicked(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });
        jPanel4.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 220, 20));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel23.setText("Correo");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 110, 26));

        jLabel21.setBackground(new java.awt.Color(204, 204, 204));
        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("Complete la información con sus datos");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, 20));

        ComboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Administrador", "Profesor", "Alumno" }));
        jPanel4.add(ComboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 220, -1));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel24.setText("Nombre de usuario");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 130, 26));

        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnEd.png"))); // NOI18N
        btnModificar.setText("Modificar  ");
        btnModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        jPanel4.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 120, -1));

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnGuardar8.png"))); // NOI18N
        btnGuardar.setText("Guardar  ");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        jPanel4.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnEli2.png"))); // NOI18N
        btnEliminar.setText("Eliminar  ");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        jPanel4.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 110, -1));

        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar (1).png"))); // NOI18N
        btnActualizar.setText("Actualizar  ");
        btnActualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });
        jPanel4.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 120, -1));

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 470, 120));

        txtIdentificacion.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtIdentificacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtIdentificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdentificacionMouseClicked(evt);
            }
        });
        txtIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificacionActionPerformed(evt);
            }
        });
        txtIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacionKeyTyped(evt);
            }
        });
        jPanel4.add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 200, -1));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel25.setText("Número de control o cédula profesional");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 250, 30));

        txtContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtContraseñaMouseClicked(evt);
            }
        });
        jPanel4.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 220, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpieza-de-datos.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jLabel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jLabel2KeyTyped(evt);
            }
        });
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        lbOjo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ojoA1.png"))); // NOI18N
        lbOjo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbOjoMouseClicked(evt);
            }
        });
        jPanel4.add(lbOjo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 30, 30));

        label2.setForeground(new java.awt.Color(255, 0, 0));
        label2.setText("Debe tener 8 caracteres y contener solo números");
        jPanel4.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 280, 40));

        label1.setForeground(new java.awt.Color(255, 0, 0));
        label1.setText("Correo electrónico no válido !");
        jPanel4.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 160, 30));

        etiNombre2.setForeground(new java.awt.Color(255, 0, 0));
        etiNombre2.setText("Solo letras");
        jPanel4.add(etiNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 60, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 500, 460));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Vector.png"))); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 90, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed

    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
                 char c = evt.getKeyChar();
                if (!Character.isLetter(c) && !Character.isWhitespace(c)) {
                    evt.consume(); 
                    etiNombre2.setVisible(true);
                }
                
                txtNombre.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
 
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
                char c = evt.getKeyChar();
                if (!Character.isLetter(c) && !Character.isWhitespace(c)) {
                    evt.consume(); 
                }
                txtApellidos.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtApellidosKeyTyped

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
 
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoKeyTyped

    private void btnVentanaAnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentanaAnteriorMouseClicked
      

    }//GEN-LAST:event_btnVentanaAnteriorMouseClicked

    private void btnVentanaAnterior1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentanaAnterior1MouseClicked
        VistaPrincipalP VentanaAnterior = new VistaPrincipalP();
        VentanaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentanaAnterior1MouseClicked

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        ModificarUsuario();

    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        try {
            guardarUsuario();
        } catch (Exception ex) {
            Logger.getLogger(VistaModificarUsuario1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        try {
            eliminarUsuario();
        } catch (Exception ex) {
            Logger.getLogger(VistaModificarUsuario1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        try {
            cargarDatosss();
        } catch (Exception ex) {
            Logger.getLogger(VistaModificarUsuario1.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void txtIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificacionActionPerformed

    private void txtIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionKeyTyped
     char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume(); 
            txtIdentificacion.setVisible(true);
        }

    }//GEN-LAST:event_txtIdentificacionKeyTyped

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        // TODO add your handling code here:
        rellenarDatos();
    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void jLabel2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2KeyTyped

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
      Limpiar();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseñaMouseClicked
        txtContraseña.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtContraseñaMouseClicked

    private void txtCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMouseClicked
        txtCorreo.setBackground(Color.WHITE);
        
        // jLabel4.setVisible(false);
    }//GEN-LAST:event_txtCorreoMouseClicked

    private void txtIdentificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdentificacionMouseClicked
       txtIdentificacion.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtIdentificacionMouseClicked

    private void lbOjoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbOjoMouseClicked
        // TODO add your handling code here:

        if (contraseñaVisible) {
            txtContraseña.setEchoChar('*');
        } else {
            txtContraseña.setEchoChar((char) 0);
        }
        contraseñaVisible = !contraseñaVisible;

    }//GEN-LAST:event_lbOjoMouseClicked

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
    
    }//GEN-LAST:event_txtUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaModificarUsuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaModificarUsuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaModificarUsuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaModificarUsuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VistaModificarUsuario1().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(VistaModificarUsuario1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboTipo;
    private javax.swing.JLabel btnActualizar;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JLabel btnModificar;
    private javax.swing.JLabel btnVentanaAnterior;
    private javax.swing.JLabel btnVentanaAnterior1;
    private javax.swing.JLabel etiNombre;
    private javax.swing.JLabel etiNombre1;
    private javax.swing.JLabel etiNombre2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel lbOjo;
    private javax.swing.JLabel msg5;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

 
public void guardarUsuario() throws Exception {
    Usuario usuario = new Usuario();

    String tipo = ComboTipo.getSelectedItem().toString().trim();
    String nombre = txtNombre.getText().trim();
    String apellidos = txtApellidos.getText().trim();
    String contraseña = txtContraseña.getText().trim();
    String correo = txtCorreo.getText().trim();
    String identificacion = txtIdentificacion.getText().trim();

    if (txtUsuario.getText().equals("") || nombre.equals("") || apellidos.equals("") || contraseña.equals("") || correo.equals("") || identificacion.equals("")) {
        JOptionPane.showMessageDialog(null, "Complete todos los campos");

        txtUsuario.setBackground(Color.RED);
        txtNombre.setBackground(Color.RED);
        txtApellidos.setBackground(Color.RED);
        txtContraseña.setBackground(Color.RED);
        txtCorreo.setBackground(Color.RED);
        txtIdentificacion.setBackground(Color.RED);

    } else if (!validador.validacionCorreo(correo)) {
        //JOptionPane.showMessageDialog(null, "Correo electrónico no válido");
        label1.setVisible(true);
        txtCorreo.setBackground(Color.RED);
    } else if (!validador.validacionContraseña(contraseña)) {
        JOptionPane.showMessageDialog(null, "Contraseña no válida. Debe contener 8 caracteres con al menos una mayúscula, una minúscula, un número y un carácter especial.");
        txtContraseña.setBackground(Color.RED);
    } else if (identificacion.length() != 8 || !identificacion.matches("\\d+")) {
        //JOptionPane.showMessageDialog(null, "La identificación debe tener 8 caracteres y contener solo números");
        label2.setVisible(true);
        txtIdentificacion.setBackground(Color.RED);
    } else {
        txtIdentificacion.setBackground(Color.WHITE);

        int identi = Integer.parseInt(identificacion);

        if (!ControladorUsuario.existeUsuario(correo)) {
            // Set user data
            usuario.setUsuario(txtUsuario.getText().trim());
            usuario.setTipo(tipo);
            usuario.setNombre(nombre);
            usuario.setApellidos(apellidos);
            usuario.setContraseña(contraseña);
            usuario.setCorreo(correo);
            usuario.setIdentificacion(identi);

            if (ControladorUsuario.insertarUsuario(usuario)) {
                JOptionPane.showMessageDialog(null, "Usuario guardado correctamente");
                Limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar el usuario");
                 
            }
        } else {
            //JOptionPane.showMessageDialog(null, "Ya existe un usuario con ese correo electrónico");
            //jLabel4.setVisible(true);
        }
    }
}



private void Limpiar() {
        txtUsuario.setText("");
        txtNombre.setText("");
        txtApellidos.setText("");
        txtContraseña.setText("");
        txtCorreo.setText("");
        txtIdentificacion.setText("");
        ComboTipo.setSelectedIndex(0);

        txtUsuario.setBackground(Color.WHITE);
        txtNombre.setBackground(Color.WHITE);
        txtApellidos.setBackground(Color.WHITE);       
        txtContraseña.setBackground(Color.WHITE);
        txtCorreo.setBackground(Color.WHITE);
         txtIdentificacion.setBackground(Color.WHITE);
         
         label1.setVisible(false);
         label2.setVisible(false);
         etiNombre1.setVisible(false);
         etiNombre2.setVisible(false);
    }

public void ModificarUsuario() {
    String usuario = txtUsuario.getText();
    String tipo = (String) ComboTipo.getSelectedItem();
    String nombre = txtNombre.getText();
    String apellidos = txtApellidos.getText();
    String contraseña = new String(txtContraseña.getPassword()).trim();
    String correo = txtCorreo.getText();
  
    String identificacion = txtIdentificacion.getText().trim();  
         int identi = Integer.parseInt(identificacion);   

    // Validar campos obligatorios
    if (usuario.isEmpty() || tipo == null || nombre.isEmpty() || apellidos.isEmpty() || contraseña.isEmpty() || correo.isEmpty() || identificacion.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Mostrar cuadro de diálogo de confirmación
    int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea realizar estos cambios?", "Confirmar Cambios", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    int selectedRow = tablaUsuarios.getSelectedRow();
    boolean actualizado = false;

    try {
        if (selectedRow >= 0) {
            // Obtener el correo del usuario seleccionado
            String correoSeleccionado = tablaUsuarios.getValueAt(selectedRow, 5).toString();

            // Obtener el objeto Usuario a partir del correo
            Usuario usuarioExistente = ControladorUsuario.getUsuario(correoSeleccionado);
            
            if (usuarioExistente != null) {
                // Actualizar los datos del usuario
                usuarioExistente.setUsuario(usuario);
                usuarioExistente.setTipo(tipo);
                usuarioExistente.setNombre(nombre);
                usuarioExistente.setApellidos(apellidos);
                usuarioExistente.setContraseña(contraseña);
                usuarioExistente.setCorreo(correo);
                usuarioExistente.setIdentificacion(identi);

                actualizado = ControladorUsuario.actualizarUsuario(usuarioExistente);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo encontrar el usuario para actualizar.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } else {
            // Crear un nuevo usuario si no hay una fila seleccionada
            Usuario nuevoUsuario = new Usuario(usuario, tipo, nombre, apellidos, contraseña, correo, identi);
            actualizado = ControladorUsuario.insertarUsuario(nuevoUsuario);
        }

        if (actualizado) {
            cargarDatos();
            Limpiar();
            JOptionPane.showMessageDialog(this, "Datos guardados correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar los datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error inesperado: " + e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();  // Añadir para ver detalles del error en la consola
    }
}















public void cargarDatos() throws Exception {
    
    List<Usuario> listaUsuarios = ControladorUsuario.obtenerUsuario();
    DefaultTableModel modeloTabla = new DefaultTableModel(
    new String[]{"Usuario", "Tipo", "Nombre", "Apellidos", "Contraseña","Correo", "Identificacion"}, 0);

    modeloTabla.setRowCount(0);
       
        for (Usuario usuario : listaUsuarios) {
            modeloTabla.addRow (new  Object[]{
                usuario.getUsuario(),
                usuario.getTipo(),
                usuario.getNombre(),
                usuario.getApellidos(),
                usuario.getContraseña(),
                usuario.getCorreo(),
                 usuario.getIdentificacion(),
               
            });
        }
         tablaUsuarios.setModel(modeloTabla);
    }




public void eliminarUsuario() throws Exception {
    int selectedRow = tablaUsuarios.getSelectedRow();
    if (selectedRow >= 0) {
        // Obtener el correo del usuario seleccionado en la tabla
        String correoSeleccionado = tablaUsuarios.getValueAt(selectedRow, 5).toString();

        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas eliminar este usuario?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            boolean eliminado = ControladorUsuario.eliminarUsuario(correoSeleccionado);
            if (eliminado) {
                cargarDatos(); // Recargar los datos de la tabla
                Limpiar(); // Limpiar los campos del formulario
                JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente.");
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar el usuario.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione un usuario de la tabla para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }
}




public void cargarDatosss() throws Exception {
    List<Usuario> listaUsuario = ControladorUsuario.obtenerUsuario();
    DefaultTableModel model = (DefaultTableModel) tablaUsuarios.getModel();
    model.setRowCount(0);

    for (Usuario usuario : listaUsuario) {
        Object[] row = new Object[7];
        row[0] = usuario.getUsuario();
        row[1] = usuario.getTipo();
        row[2] = usuario.getNombre();
        row[3] = usuario.getApellidos();
        row[4] = usuario.getContraseña();
        row[5] = usuario.getCorreo();
        row[6] = usuario.getIdentificacion();
        
        model.addRow(row);
    }
}


public void rellenarDatos() {
    int selectedRow = tablaUsuarios.getSelectedRow();
    if (selectedRow >= 0) {
        txtUsuario.setText(tablaUsuarios.getValueAt(selectedRow, 0).toString());
        ComboTipo.setSelectedItem(tablaUsuarios.getValueAt(selectedRow, 1).toString());
        txtNombre.setText(tablaUsuarios.getValueAt(selectedRow, 2).toString());
        txtApellidos.setText(tablaUsuarios.getValueAt(selectedRow, 3).toString());
        txtContraseña.setText(tablaUsuarios.getValueAt(selectedRow, 4).toString()); // Maneja esto con cuidado
        txtCorreo.setText(tablaUsuarios.getValueAt(selectedRow, 5).toString());
        txtIdentificacion.setText(tablaUsuarios.getValueAt(selectedRow, 6).toString());
    }
}









}

