/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Validaciones.validacion;
import conexion.Conexion;
import controlador.ControladorUsuario;
import java.awt.Color;
import static java.awt.Color.RED;
import java.awt.Dimension;
import java.sql.Statement;
import modelo.Usuario;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import controlador.PasswordUtil;
//import java.sql.Statement;

/**
 *
 * @author Itzel_CG
 */
public class VistaRegistroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistroUsuario
     */
    private final validacion validador;
    private boolean contraseñaVisible = false;
    
    public VistaRegistroUsuario() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Registro Usuario- SISTEMA DE LA INSTITUCIÓN");
        this.setSize(new Dimension (900, 550));
        validador = new validacion();
        lblObligatorio1.setVisible(false);
        lblObligatorio2.setVisible(false);
        lblObligatorio3.setVisible(false);
        lblObligatorio4.setVisible(false);
        lblObligatorio5.setVisible(false);
        lblObligatorio6.setVisible(false);
        lblObligatorio7.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVentanaAnterior = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnVentanaAnterior1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        imgGuardar = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        msg5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtGuardar = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ComboTipo = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        lbOjo = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        lblObligatorio1 = new javax.swing.JLabel();
        lblObligatorio2 = new javax.swing.JLabel();
        lblObligatorio3 = new javax.swing.JLabel();
        lblObligatorio4 = new javax.swing.JLabel();
        lblObligatorio5 = new javax.swing.JLabel();
        lblObligatorio6 = new javax.swing.JLabel();
        lblObligatorio7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        btnVentanaAnterior.setFont(new java.awt.Font("Ebrima", 1, 13)); // NOI18N
        btnVentanaAnterior.setForeground(new java.awt.Color(255, 255, 255));
        btnVentanaAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anterior.png"))); // NOI18N
        btnVentanaAnterior.setText("Ventana anterior");
        btnVentanaAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentanaAnteriorMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(1, 25, 71));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(1, 25, 71));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 30));

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(350, 600));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 148, -1, 223));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/i6.1.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Ebrima", 1, 32)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("EscuelaConnect ");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        btnVentanaAnterior1.setFont(new java.awt.Font("Ebrima", 1, 13)); // NOI18N
        btnVentanaAnterior1.setForeground(new java.awt.Color(255, 255, 255));
        btnVentanaAnterior1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anterior.png"))); // NOI18N
        btnVentanaAnterior1.setText("Ventana anterior");
        btnVentanaAnterior1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentanaAnterior1MouseClicked(evt);
            }
        });
        jPanel3.add(btnVentanaAnterior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 270, 460));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(0, 51, 102));
        jLabel13.setFont(new java.awt.Font("Ebrima", 1, 26)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 102));
        jLabel13.setText("Nuevo Usuario");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -5, -1, 50));

        txtNombre.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel4.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 310, -1));

        imgGuardar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        imgGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        imgGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgGuardarMouseClicked(evt);
            }
        });
        jPanel4.add(imgGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 70, 80));

        txtApellidos.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtApellidos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidosFocusLost(evt);
            }
        });
        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });
        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });
        jPanel4.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 310, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Apellidos");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 110, 26));

        msg5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        msg5.setForeground(new java.awt.Color(255, 0, 0));
        msg5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel4.add(msg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("Nombres");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 73, 26));

        txtGuardar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtGuardar.setText("Guardar");
        txtGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGuardarMouseClicked(evt);
            }
        });
        jPanel4.add(txtGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 60, 20));

        txtUsuario.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        jPanel4.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 310, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel16.setText("Tipo de usuario");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 130, 26));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel20.setText("Contraseña");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 110, 26));

        txtCorreo.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtCorreo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });
        jPanel4.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 310, -1));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel23.setText("Correo");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 110, 26));

        jLabel21.setBackground(new java.awt.Color(204, 204, 204));
        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("Complete la información con sus datos");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 210, 30));

        ComboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Administrador", "Profesor", "Alumno" }));
        ComboTipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ComboTipoFocusLost(evt);
            }
        });
        jPanel4.add(ComboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 310, -1));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel24.setText("Nombre de usuario");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 130, 26));

        txtIdentificacion.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtIdentificacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtIdentificacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdentificacionFocusLost(evt);
            }
        });
        txtIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificacionActionPerformed(evt);
            }
        });
        txtIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacionKeyTyped(evt);
            }
        });
        jPanel4.add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 310, -1));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel25.setText("Número de  control o cédula profesional");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 310, 26));

        lbOjo.setBackground(new java.awt.Color(255, 255, 153));
        lbOjo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ojoA1.png"))); // NOI18N
        lbOjo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbOjoMouseClicked(evt);
            }
        });
        jPanel4.add(lbOjo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 40, 40));

        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        txtContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContraseñaKeyTyped(evt);
            }
        });
        jPanel4.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 310, 30));

        lblObligatorio1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblObligatorio1.setForeground(new java.awt.Color(204, 0, 51));
        lblObligatorio1.setText("*obligatorio");
        jPanel4.add(lblObligatorio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 70, 20));

        lblObligatorio2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblObligatorio2.setForeground(new java.awt.Color(204, 0, 51));
        lblObligatorio2.setText("*obligatorio");
        jPanel4.add(lblObligatorio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 70, 20));

        lblObligatorio3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblObligatorio3.setForeground(new java.awt.Color(204, 0, 51));
        lblObligatorio3.setText("*obligatorio");
        jPanel4.add(lblObligatorio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 70, 20));

        lblObligatorio4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblObligatorio4.setForeground(new java.awt.Color(204, 0, 51));
        lblObligatorio4.setText("*obligatorio");
        jPanel4.add(lblObligatorio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 70, 20));

        lblObligatorio5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblObligatorio5.setForeground(new java.awt.Color(204, 0, 51));
        lblObligatorio5.setText("*obligatorio");
        jPanel4.add(lblObligatorio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 70, 20));

        lblObligatorio6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblObligatorio6.setForeground(new java.awt.Color(204, 0, 51));
        lblObligatorio6.setText("*obligatorio");
        jPanel4.add(lblObligatorio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 70, 20));

        lblObligatorio7.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblObligatorio7.setForeground(new java.awt.Color(204, 0, 51));
        lblObligatorio7.setText("*obligatorio");
        jPanel4.add(lblObligatorio7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 70, 20));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 500, 460));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Vector.png"))); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 90, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed

    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
                 char c = evt.getKeyChar();
                if (!Character.isLetter(c) && !Character.isWhitespace(c)) {
                    evt.consume(); 
                }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
 
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
                char c = evt.getKeyChar();
                if (!Character.isLetter(c) && !Character.isWhitespace(c)) {
                    evt.consume(); 
                }
    }//GEN-LAST:event_txtApellidosKeyTyped

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        char input=evt.getKeyChar();
        if(!Character.isLetter(input)&&!Character.isISOControl(input)){
            evt.consume();
        }
        txtUsuario.setBackground(Color.WHITE);      
               
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped
                                                 
        
        if(val.validacionCorreo(txtCorreo.getText())){
            lblObligatorio7.setVisible(false);
        }else{
            lblObligatorio7.setVisible(true);
        }
    
    }//GEN-LAST:event_txtCorreoKeyTyped

    private void txtGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGuardarMouseClicked

    }//GEN-LAST:event_txtGuardarMouseClicked

    private void imgGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgGuardarMouseClicked
        try {
            guardarUsuario();
        } catch (Exception ex) {
            Logger.getLogger(VistaRegistroUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_imgGuardarMouseClicked

    private void btnVentanaAnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentanaAnteriorMouseClicked
      

    }//GEN-LAST:event_btnVentanaAnteriorMouseClicked

    private void btnVentanaAnterior1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentanaAnterior1MouseClicked
         VistaLogin VistaLogin = new VistaLogin();
        VistaLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentanaAnterior1MouseClicked

    private void txtIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificacionActionPerformed

    private void txtIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionKeyTyped
        char input = evt.getKeyChar();
    // Verificar si el carácter ingresado es un dígito o una tecla de control (como borrar, retroceso, etc.)
    if (!Character.isDigit(input) && !Character.isISOControl(input)) {
        evt.consume(); // Consumir el evento si el carácter no es válido
    }
    }//GEN-LAST:event_txtIdentificacionKeyTyped

    private void lbOjoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbOjoMouseClicked
        // TODO add your handling code here:

        if (contraseñaVisible) {
            txtContraseña.setEchoChar('*');
        } else {
            txtContraseña.setEchoChar((char) 0);
        }
        contraseñaVisible = !contraseñaVisible;

    }//GEN-LAST:event_lbOjoMouseClicked

    private void ComboTipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ComboTipoFocusLost
       if(ComboTipo.getSelectedIndex()==0){
            lblObligatorio3.setVisible(true);
        }else{
            lblObligatorio3.setVisible(false);
        }
    }//GEN-LAST:event_ComboTipoFocusLost

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        if(txtUsuario.getText().trim().isEmpty()){
            lblObligatorio2.setVisible(true);
        }else{
            lblObligatorio2.setVisible(false);
        }
        
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        if(txtNombre.getText().trim().isEmpty()){
            lblObligatorio4.setVisible(true);
        }else{
            lblObligatorio4.setVisible(false);
        }
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidosFocusLost
        if(txtApellidos.getText().trim().isEmpty()){
            lblObligatorio5.setVisible(true);
        }else{
            lblObligatorio5.setVisible(false);
        }
    }//GEN-LAST:event_txtApellidosFocusLost
validacion val = new validacion();
    private void txtContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseñaKeyTyped
         String te=new String(txtContraseña.getPassword());
        if(val.validacionContraseña(te)){
            lblObligatorio6.setVisible(false);
        }else{
            lblObligatorio6.setVisible(true);
        }
    }//GEN-LAST:event_txtContraseñaKeyTyped

    private void txtIdentificacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdentificacionFocusLost
        // TODO add your handling code here:validreg
        if(txtIdentificacion.getText().isEmpty()){
            lblObligatorio1.setVisible(true);
        }else{
            lblObligatorio1.setVisible(false);
        }
    }//GEN-LAST:event_txtIdentificacionFocusLost

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboTipo;
    private javax.swing.JLabel btnVentanaAnterior;
    private javax.swing.JLabel btnVentanaAnterior1;
    private javax.swing.JLabel imgGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbOjo;
    private javax.swing.JLabel lblObligatorio1;
    private javax.swing.JLabel lblObligatorio2;
    private javax.swing.JLabel lblObligatorio3;
    private javax.swing.JLabel lblObligatorio4;
    private javax.swing.JLabel lblObligatorio5;
    private javax.swing.JLabel lblObligatorio6;
    private javax.swing.JLabel lblObligatorio7;
    private javax.swing.JLabel msg5;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JLabel txtGuardar;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

public void guardarUsuario() throws Exception {
    Usuario usuario = new Usuario();
    PasswordUtil encrip= new PasswordUtil();
    
    
    String tipo = ComboTipo.getSelectedItem().toString().trim();
    String nombre = txtNombre.getText().trim();
    String apellidos = txtApellidos.getText().trim();
    String contraseña = txtContraseña.getText().trim();
    String correo = txtCorreo.getText().trim();
    String identificacion = txtIdentificacion.getText().trim();

    if (txtUsuario.getText().equals("") || nombre.equals("") || apellidos.equals("") || contraseña.equals("") || correo.equals("") || identificacion.equals("")) {
        JOptionPane.showMessageDialog(null, "Complete todos los campos");

        txtUsuario.setBackground(Color.RED);
        txtNombre.setBackground(Color.RED);
        txtApellidos.setBackground(Color.RED);
        txtContraseña.setBackground(Color.RED);
        txtCorreo.setBackground(Color.RED);
        txtIdentificacion.setBackground(Color.RED);

    } else if (!validador.validacionCorreo(correo)) {
        JOptionPane.showMessageDialog(null, "Correo electrónico no válido");
        txtCorreo.setBackground(Color.RED);
    } else if (!validador.validacionContraseña(contraseña)) {
        JOptionPane.showMessageDialog(null, "Contraseña no válida. Debe contener 8 caracteres con al menos una mayúscula, una minúscula, un número y un carácter especial.");
        txtContraseña.setBackground(Color.RED);
    } else if (identificacion.length() != 8 || !identificacion.matches("\\d+")) {
        JOptionPane.showMessageDialog(null, "La identificación debe tener 8 caracteres y contener solo números");
        txtIdentificacion.setBackground(Color.RED);
    } else {
        txtIdentificacion.setBackground(Color.WHITE);

        int identi = Integer.parseInt(identificacion);

        if (!ControladorUsuario.existeUsuario(correo)) {
            // Set user data
            usuario.setUsuario(txtUsuario.getText().trim());
            usuario.setTipo(tipo);
            usuario.setNombre(nombre);
            usuario.setApellidos(apellidos);
            usuario.setContraseña(encrip.hashPassword(contraseña));
            usuario.setCorreo(correo);
            usuario.setIdentificacion(identi);

            if (ControladorUsuario.insertarUsuario(usuario)) {
                JOptionPane.showMessageDialog(null, "Usuario guardado correctamente");
                Limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar el usuario");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ya existe un usuario con ese correo electrónico");
        }
    }
}


private void Limpiar() {
        txtUsuario.setText("");
        txtNombre.setText("");
        txtApellidos.setText("");
        txtContraseña.setText("");
        txtCorreo.setText("");
        txtIdentificacion.setText("");
        ComboTipo.setSelectedIndex(0);

        txtUsuario.setBackground(Color.WHITE);
        txtNombre.setBackground(Color.WHITE);
        txtApellidos.setBackground(Color.WHITE);       
        txtContraseña.setBackground(Color.WHITE);
        txtCorreo.setBackground(Color.WHITE);
         txtIdentificacion.setBackground(Color.WHITE);
    }
}