/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;



import controlador.ControladorProfesor;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Profesor;



/**
 *
 * @author Itzel_CG
 */
public class VistaRegistroProfesor extends javax.swing.JFrame {
    
 //private ModeloTablaProfesor modeloTabla;
    
    private Profesor profesorSeleccionado;
    
    public VistaRegistroProfesor() {
        initComponents();
         this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Registro Profesor- SISTEMA DE LA INSTITUCIÓN");
        this.setSize(new Dimension (900, 550));
        cargarDatos();
        
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupo = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnVentanaAnterior = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNumeroTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtApellidoM = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        msg5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProfesor = new javax.swing.JTable();
        btnEliminar = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JLabel();
        btnModificar = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JLabel();
        txtDomicilio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtEspecialidad = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(1, 25, 71));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(1, 25, 71));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Profesor");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 30));

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(350, 600));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 148, -1, 223));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/i6.1.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 250, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Ebrima", 1, 32)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("EscuelaConnect ");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        btnVentanaAnterior.setFont(new java.awt.Font("Ebrima", 1, 13)); // NOI18N
        btnVentanaAnterior.setForeground(new java.awt.Color(255, 255, 255));
        btnVentanaAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anterior.png"))); // NOI18N
        btnVentanaAnterior.setText("Ventana anterior");
        btnVentanaAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentanaAnteriorMouseClicked(evt);
            }
        });
        jPanel3.add(btnVentanaAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 250, 470));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(0, 51, 102));
        jLabel13.setFont(new java.awt.Font("Ebrima", 1, 26)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 102));
        jLabel13.setText("Registro profesor");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        txtNombre.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel4.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 150, 20));

        txtApellidoP.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtApellidoP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPActionPerformed(evt);
            }
        });
        txtApellidoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoPKeyTyped(evt);
            }
        });
        jPanel4.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 160, 20));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Apellido Paterno");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 110, -1));

        txtNumeroTelefono.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtNumeroTelefono.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNumeroTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroTelefonoActionPerformed(evt);
            }
        });
        txtNumeroTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroTelefonoKeyTyped(evt);
            }
        });
        jPanel4.add(txtNumeroTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 170, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setText("Número de teléfono");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, 26));

        txtApellidoM.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtApellidoM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApellidoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMActionPerformed(evt);
            }
        });
        txtApellidoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoMKeyTyped(evt);
            }
        });
        jPanel4.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 170, 20));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setText("Apellido Materno");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 110, 20));

        msg5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        msg5.setForeground(new java.awt.Color(255, 0, 0));
        msg5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel4.add(msg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("Nombre");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 73, 20));

        tablaProfesor.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tablaProfesor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProfesor.setToolTipText("");
        tablaProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProfesorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaProfesor);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 500, 100));

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnEli2.png"))); // NOI18N
        btnEliminar.setText("Eliminar  ");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        jPanel4.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, -1));

        txtCedula.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtCedula.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        jPanel4.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 150, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel17.setText("Cédula");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 120, 26));

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnGuardar8.png"))); // NOI18N
        btnGuardar.setText("Guardar   ");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        jPanel4.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnEd.png"))); // NOI18N
        btnModificar.setText("Modificar  ");
        btnModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        jPanel4.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));

        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar (1).png"))); // NOI18N
        btnActualizar.setText("Actualizar  ");
        btnActualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });
        jPanel4.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, -1, -1));

        txtDomicilio.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtDomicilio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDomicilioActionPerformed(evt);
            }
        });
        txtDomicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDomicilioKeyTyped(evt);
            }
        });
        jPanel4.add(txtDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 500, 20));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setText("Domicilio");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 20));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel18.setText("Especialidad");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 120, 26));

        txtEspecialidad.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtEspecialidad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecialidadActionPerformed(evt);
            }
        });
        txtEspecialidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEspecialidadKeyTyped(evt);
            }
        });
        jPanel4.add(txtEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 150, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 530, 470));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Vector.png"))); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 180, 630));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped

    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPActionPerformed

    private void txtApellidoPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPKeyTyped

    private void txtApellidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMActionPerformed

    private void txtApellidoMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoMKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMKeyTyped

    private void txtNumeroTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroTelefonoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroTelefonoKeyTyped

    private void txtNumeroTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroTelefonoActionPerformed

    private void btnVentanaAnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentanaAnteriorMouseClicked
        VistaPrincipalP ventanaPrincipal = new VistaPrincipalP();
        ventanaPrincipal.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnVentanaAnteriorMouseClicked

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
      eliminarProfesor();
        
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
       guardarProfesor();
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
       
         if (profesorSeleccionado == null){
        JOptionPane.showMessageDialog(null, "Seleccione un Profesor" );
       }else {
           if (txtNombre.getText().isEmpty() || txtApellidoP.getText().isEmpty() ||  txtApellidoM.getText().isEmpty() ||   txtDomicilio.getText().isEmpty() || txtNumeroTelefono.getText().isEmpty() ||  txtEspecialidad.getText().isEmpty() ||  txtCedula.getText().isEmpty()  ){
            JOptionPane.showMessageDialog(null, "Completa todos los campos" );
     
           }else {
           
                profesorSeleccionado.setNombre(txtNombre.getText().trim());
                profesorSeleccionado.setApellidoP(txtApellidoP.getText().trim());
                profesorSeleccionado.setApellidoM(txtApellidoM.getText().trim());
                profesorSeleccionado.setDireccion(txtDomicilio.getText().trim());
                profesorSeleccionado.setTelefono(txtNumeroTelefono.getText().trim());
                profesorSeleccionado.setEspecialidad(txtEspecialidad.getText().trim());
                profesorSeleccionado.setCedula(txtCedula.getText().trim());
                
                if (ControladorProfesor.actualizarProfesor(profesorSeleccionado, profesorSeleccionado.getCedula())){
                 JOptionPane.showMessageDialog(null, "Actualización Exitosa!" );
     
                 this.cargarDatos();
                 
                 this.Limpiar();
                }else {
                
                     JOptionPane.showMessageDialog(null, "¡!" );
     
                }
                
                
           }
       
       }
       
       
       
    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
     
       cargarDatosss();
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void txtDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDomicilioActionPerformed

    private void txtDomicilioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDomicilioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDomicilioKeyTyped

    private void txtEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecialidadActionPerformed

    private void txtEspecialidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEspecialidadKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecialidadKeyTyped

    private void tablaProfesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProfesorMouseClicked
        if (evt.getClickCount() == 2) { // Doble clic en la tabla
                   int filaSeleccionada = tablaProfesor.getSelectedRow();
                   if (filaSeleccionada >= 0) {
                       String cedula = tablaProfesor.getValueAt(filaSeleccionada, 7).toString();
                       profesorSeleccionado = ControladorProfesor.obtenerProfesorPorCedula(cedula);
                       if (profesorSeleccionado != null) {
                           llenarCampos(profesorSeleccionado);
                       } else {
                           JOptionPane.showMessageDialog(null, "No se encontró el profesor");
                       }
                   }
               }   
    }//GEN-LAST:event_tablaProfesorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistroProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnActualizar;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.ButtonGroup btnGrupo;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JLabel btnModificar;
    private javax.swing.JLabel btnVentanaAnterior;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel msg5;
    private javax.swing.JTable tablaProfesor;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroTelefono;
    // End of variables declaration//GEN-END:variables



private void Limpiar() {
        
        txtNombre.setText("");
        txtApellidoP.setText("");
        txtApellidoM.setText("");
        txtDomicilio.setText("");
        txtNumeroTelefono.setText("");
        txtCedula.setText("");
        txtEspecialidad.setText("");
    }


public void guardarProfesor() {

    Profesor profesor = new Profesor();
    ControladorProfesor ContrProfesor = new ControladorProfesor();

    String nombre = txtNombre.getText().trim();
    String apellidoP = txtApellidoP.getText().trim();
    String apellidoM = txtApellidoM.getText().trim();
    String direccion = txtDomicilio.getText().trim();
    String telefono = txtNumeroTelefono.getText().trim();
    String especialidad = txtEspecialidad.getText().trim();
    String cedula = txtCedula.getText().trim();
  

    if (nombre.equals("") || apellidoP.equals("") || apellidoM.equals("") || direccion.equals ("") || telefono.equals("") || 
               especialidad.equals("" ) ||  cedula.equals("" )) {
        JOptionPane.showMessageDialog(null, "Complete todos los campos");
    } else {
        if (!ContrProfesor.existeProfesor(cedula)) {
            profesor.setNombre(nombre);
            profesor.setApellidoP(apellidoP);
            profesor.setApellidoM(apellidoM);
            profesor.setDireccion(direccion);
            profesor.setTelefono(telefono);
            profesor.setEspecialidad(especialidad);
            profesor.setCedula(cedula);
           

            if (ContrProfesor.insertarProfesor(profesor)) {
                JOptionPane.showMessageDialog(null, "Profesor guardado correctamente");
                Limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar el profesor");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ya existe un alumno con ese nombre completo");
        }
    }
    
}




public void cargarDatos() {
    
    List<Profesor> listaProfesor = ControladorProfesor.obtenerProfesor();
    DefaultTableModel modeloTabla = new DefaultTableModel(
    new String[]{"Nombre", "Apellido paterno", "Apellido materno", "Domicilio", "Teléfono", "Especialidad", "Cédula"}, 0);

    modeloTabla.setRowCount(0);
       
        for (Profesor profesor : listaProfesor) {
            modeloTabla.addRow (new  Object[]{
                profesor.getNombre(),
                profesor.getApellidoP(),
                profesor.getApellidoM(),
                profesor.getDireccion(),
                profesor.getTelefono(),
                profesor.getEspecialidad(),
                profesor.getCedula(),    
                    
            });
        }
         tablaProfesor.setModel(modeloTabla);
    }





  

public void eliminarProfesor() {
    int selectedRow = tablaProfesor.getSelectedRow();
    if (selectedRow >= 0) {
        String cedulaSeleccionada = tablaProfesor.getValueAt(selectedRow, 6).toString(); 
        
        int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas eliminar este profesor?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            boolean eliminado = ControladorProfesor.eliminarProfesor(cedulaSeleccionada);
            if (eliminado) {
                cargarDatos();
                JOptionPane.showMessageDialog(this, "Profesor eliminado correctamente.");
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar el profesor.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecciona un profesor para eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}




    public void cargarDatosss() {
        List<Profesor> listaProfesor = ControladorProfesor.obtenerProfesor();
        DefaultTableModel model = (DefaultTableModel) tablaProfesor.getModel();
        model.setRowCount(0);

        for (Profesor profesor : listaProfesor) {
            Object[] row = new Object[7];

             row[0] = profesor.getNombre();   
             row[1] = profesor.getApellidoP();
             row[2] = profesor.getApellidoM();
             row[3] = profesor.getDireccion();
             row[4] = profesor.getTelefono();
             row[5] = profesor.getEspecialidad();
             row[6] = profesor.getCedula();

            model.addRow(row);
        }
    }

    

    private void llenarCampos(Profesor profesor) {
        
    txtNombre.setText(profesor.getNombre());
    txtApellidoP.setText(profesor.getApellidoP());
    txtApellidoM.setText(profesor.getApellidoM());
    txtDomicilio.setText(profesor.getDireccion());
    txtNumeroTelefono.setText(profesor.getTelefono());
    txtEspecialidad.setText(profesor.getEspecialidad());
    txtCedula.setText(profesor.getCedula());
    
    }





}
    














/**

 private void modificarProfesor() {
        int filaSeleccionada = tablaProfesor.getSelectedRow();
        if (filaSeleccionada != -1) {
            String cedula = txtCedula.getText(); 

           // Profesor profesor = new Profesor(
               
                txtNombre.getText(),
                txtApellidoP.getText(),
                txtApellidoM.getText(),
                txtDomicilio.getText(),
                txtNumeroTelefono.getText(),
                txtEspecialidad.getText(),
                cedula
            );

            boolean exito = ControladorProfesor.modificarProfesor(profesor);
            if (exito) {
                JOptionPane.showMessageDialog(null, "Profesor modificado exitosamente");
                
                
                tablaProfesor.setValueAt(profesor.getNombre(), filaSeleccionada, 1);
                tablaProfesor.setValueAt(profesor.getApellidoP(), filaSeleccionada, 2);
                tablaProfesor.setValueAt(profesor.getApellidoM(), filaSeleccionada, 3);
                tablaProfesor.setValueAt(profesor.getDireccion(), filaSeleccionada, 4);
                tablaProfesor.setValueAt(profesor.getTelefono(), filaSeleccionada, 5);
                tablaProfesor.setValueAt(profesor.getEspecialidad(), filaSeleccionada, 6);
                tablaProfesor.setValueAt(profesor.getCedula(), filaSeleccionada, 7);
            } else {
                JOptionPane.showMessageDialog(null, "Error al modificar el profesor" );
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un profesor de la tabla");
        }
    }





}
 */