/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorAlumno;
import java.awt.Dimension;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import modelo.Alumno;


/**
 *
 * @author Itzel_CG
 */
public final class VistaRegistroAlumno extends javax.swing.JFrame {

    
    public VistaRegistroAlumno() {
        initComponents();
         this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Registro Alumno- SISTEMA DE LA INSTITUCIÓN");
        this.setSize(new Dimension (900, 560));
        cargarDatos();
        
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupo = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnVentanaAnterior = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtControl = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNumeroTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtApellidoM = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        calendario = new com.toedter.calendar.JDateChooser();
        msg5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnMasculino = new javax.swing.JRadioButton();
        btnFemenino = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAlumno = new javax.swing.JTable();
        btnEliminar = new javax.swing.JLabel();
        txtTutor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtOcupacion = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JLabel();
        btnModificar = new javax.swing.JLabel();
        btnEliminar1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtGrupo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtBoleta = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(1, 25, 71));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(1, 25, 71));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Alumnos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 30));

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(350, 600));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 148, -1, 223));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/i6.1.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 250, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Ebrima", 1, 32)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("EscuelaConnect ");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        btnVentanaAnterior.setFont(new java.awt.Font("Ebrima", 1, 13)); // NOI18N
        btnVentanaAnterior.setForeground(new java.awt.Color(255, 255, 255));
        btnVentanaAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anterior.png"))); // NOI18N
        btnVentanaAnterior.setText("Ventana anterior");
        btnVentanaAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentanaAnteriorMouseClicked(evt);
            }
        });
        jPanel3.add(btnVentanaAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 250, 490));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(0, 51, 102));
        jLabel13.setFont(new java.awt.Font("Ebrima", 1, 26)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 102));
        jLabel13.setText("Registro alumno");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        txtControl.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtControl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtControlActionPerformed(evt);
            }
        });
        txtControl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtControlKeyTyped(evt);
            }
        });
        jPanel4.add(txtControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 170, 20));

        txtApellidoP.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtApellidoP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPActionPerformed(evt);
            }
        });
        txtApellidoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoPKeyTyped(evt);
            }
        });
        jPanel4.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 160, 20));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Apellido Paterno");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 110, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Fecha de nacimiento");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 20));

        txtNumeroTelefono.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtNumeroTelefono.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNumeroTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroTelefonoActionPerformed(evt);
            }
        });
        txtNumeroTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroTelefonoKeyTyped(evt);
            }
        });
        jPanel4.add(txtNumeroTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 200, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setText("Número de teléfono");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 120, 26));

        txtApellidoM.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtApellidoM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApellidoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMActionPerformed(evt);
            }
        });
        txtApellidoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoMKeyTyped(evt);
            }
        });
        jPanel4.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 170, 20));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setText("Apellido Materno");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 110, 20));
        jPanel4.add(calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 150, -1));

        msg5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        msg5.setForeground(new java.awt.Color(255, 0, 0));
        msg5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel4.add(msg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setText("Genero");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 60, 30));

        btnGrupo.add(btnMasculino);
        btnMasculino.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnMasculino.setText("Masculino");
        btnMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasculinoActionPerformed(evt);
            }
        });
        jPanel4.add(btnMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 90, -1));

        btnGrupo.add(btnFemenino);
        btnFemenino.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnFemenino.setText("Femenino");
        jPanel4.add(btnFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("Número de control");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 130, 20));

        tablaAlumno.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tablaAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaAlumno.setToolTipText("");
        tablaAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAlumnoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaAlumno);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 500, 110));

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnEli2.png"))); // NOI18N
        btnEliminar.setText("Eliminar  ");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        jPanel4.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, -1));

        txtTutor.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtTutor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTutorActionPerformed(evt);
            }
        });
        txtTutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTutorKeyTyped(evt);
            }
        });
        jPanel4.add(txtTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 290, 20));

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DATOS DEL TUTOR");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 500, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel16.setText("Nombre completo del tutor");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 190, -1));

        txtCorreo.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtCorreo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });
        jPanel4.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 270, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel17.setText("Correo electrónico");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 120, 26));

        txtOcupacion.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtOcupacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtOcupacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOcupacionActionPerformed(evt);
            }
        });
        txtOcupacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOcupacionKeyTyped(evt);
            }
        });
        jPanel4.add(txtOcupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 180, 20));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel18.setText("Ocupación");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 80, 26));

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnGuardar8.png"))); // NOI18N
        btnGuardar.setText("Guardar   ");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        jPanel4.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnEd.png"))); // NOI18N
        btnModificar.setText("Modificar  ");
        btnModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        jPanel4.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, -1));

        btnEliminar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar (1).png"))); // NOI18N
        btnEliminar1.setText("Actualizar  ");
        btnEliminar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminar1MouseClicked(evt);
            }
        });
        jPanel4.add(btnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, -1, -1));

        txtNombre.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel4.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 150, 20));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setText("Nombre");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 73, 20));

        txtGrupo.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtGrupo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrupoActionPerformed(evt);
            }
        });
        txtGrupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGrupoKeyTyped(evt);
            }
        });
        jPanel4.add(txtGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 180, 20));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel19.setText("Gupo Asignado");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 100, 26));

        txtBoleta.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtBoleta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBoletaActionPerformed(evt);
            }
        });
        txtBoleta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBoletaKeyTyped(evt);
            }
        });
        jPanel4.add(txtBoleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 180, -1));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel20.setText("Id Boleta");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 100, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 530, 490));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Vector.png"))); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 180, 630));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtControlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtControlActionPerformed

    private void txtControlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtControlKeyTyped

    }//GEN-LAST:event_txtControlKeyTyped

    private void txtApellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPActionPerformed

    private void txtApellidoPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPKeyTyped

    private void txtApellidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMActionPerformed

    private void txtApellidoMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoMKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMKeyTyped

    private void txtNumeroTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroTelefonoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroTelefonoKeyTyped

    private void txtNumeroTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroTelefonoActionPerformed

    private void btnMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMasculinoActionPerformed

    private void btnVentanaAnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentanaAnteriorMouseClicked
        VistaPrincipalP ventanaPrincipal = new VistaPrincipalP();
        ventanaPrincipal.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnVentanaAnteriorMouseClicked

    private void txtTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTutorActionPerformed

    private void txtTutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTutorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTutorKeyTyped

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoKeyTyped

    private void txtOcupacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOcupacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOcupacionActionPerformed

    private void txtOcupacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOcupacionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOcupacionKeyTyped

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
      eliminarAlumno();
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
       guardarAlumno();
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        ModificarAlumno();
        
    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnEliminar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminar1MouseClicked
    cargarDatos2();       
        //mostrarAlumnoRecienInsertado(txtCorreo.getText());       
    }//GEN-LAST:event_btnEliminar1MouseClicked

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyTyped

    private void tablaAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAlumnoMouseClicked
       rellenarDatos();
    }//GEN-LAST:event_tablaAlumnoMouseClicked

    private void txtGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrupoActionPerformed

    private void txtGrupoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrupoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrupoKeyTyped

    private void txtBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoletaActionPerformed

    private void txtBoletaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBoletaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoletaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistroAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel btnEliminar1;
    private javax.swing.JRadioButton btnFemenino;
    private javax.swing.ButtonGroup btnGrupo;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JRadioButton btnMasculino;
    private javax.swing.JLabel btnModificar;
    private javax.swing.JLabel btnVentanaAnterior;
    private com.toedter.calendar.JDateChooser calendario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel msg5;
    private javax.swing.JTable tablaAlumno;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtBoleta;
    private javax.swing.JTextField txtControl;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtGrupo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroTelefono;
    private javax.swing.JTextField txtOcupacion;
    private javax.swing.JTextField txtTutor;
    // End of variables declaration//GEN-END:variables



private void Limpiar() {
        
        txtControl.setText("");
        txtNombre.setText("");
        txtApellidoP.setText("");
        txtApellidoM.setText("");
        calendario.setDate(null);
        btnMasculino.setSelected(true);
        btnFemenino.setSelected(false);
        txtNumeroTelefono.setText("");
        txtTutor.setText("");
        txtOcupacion.setText("");
        txtCorreo.setText("");
        txtGrupo.setText("");
    }



public void guardarAlumno() {

    Alumno alumno = new Alumno();
    ControladorAlumno ContrAlumno = new ControladorAlumno();
    
   // Assuming txtControl is a JTextField or similar
    String controlText = txtControl.getText().trim();  
    int control = Integer.parseInt(controlText);       

    String nombre = txtNombre.getText().trim();
    String apellidoP = txtApellidoP.getText().trim();
    String apellidoM = txtApellidoM.getText().trim();
    Date fecha = calendario.getDate();
    String fechaNacimiento  = String.format("%1$td %1$tB %1$tY", fecha);
    String genero = "";
    
    String tutor = txtTutor.getText().trim();
    String ocupacion = txtOcupacion.getText().trim();
    String numeroTel = txtNumeroTelefono.getText().trim();
    String correo = txtCorreo.getText().trim();
    String grupo = txtGrupo.getText().trim();
  
    
    if (btnMasculino.isSelected()) {
        genero = "Masculino";
    } else if (btnFemenino.isSelected()) {
        genero = "Femenino";
    }

    if (controlText.equals("") || nombre.equals("") || apellidoP.equals("") || apellidoM.equals("") || fechaNacimiento.equals ("") || genero.equals("") || 
               tutor.equals("" ) ||  ocupacion.equals("" ) || numeroTel.equals("" ) || correo.equals("" ) || grupo.equals("" ) ) {
        JOptionPane.showMessageDialog(null, "Complete todos los campos");
    } else {
        if (!ControladorAlumno.existeAlumno(controlText)) {
            
            alumno.setIdAlumno(control);
            alumno.setNombre(nombre);
            alumno.setApellidoP(apellidoP);
            alumno.setApellidoM(apellidoM);
            alumno.setFechaNaci(fechaNacimiento);
            alumno.setGenero(genero);
            alumno.setTutor(tutor);
            alumno.setOcupacion(ocupacion);
            alumno.setTelefono(numeroTel);
            alumno.setCorreo(correo);
            alumno.setIdGrupo(grupo);
            

            if (ContrAlumno.insertarAlumno(alumno)) {
                JOptionPane.showMessageDialog(null, "Alumno guardado correctamente");
                Limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar el alumno");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ya existe un alumno con ese nombre completo");
        }
    }
    
}



public void ModificarAlumno() {
    String controlText = txtControl.getText().trim();  
    int control = Integer.parseInt(controlText);       

    
    String nombre = txtNombre.getText();
    String apellidoP = txtApellidoP.getText();
    String apellidoM = txtApellidoM.getText();
    Date fecha = calendario.getDate();
    String fechaNacimiento = String.format("%1$td %1$tB %1$tY", fecha);
    String telefono = txtNumeroTelefono.getText();
    String genero = btnMasculino.isSelected() ? "Masculino" : "Femenino";
    String tutor = txtTutor.getText();
    String correo = txtCorreo.getText();
    String ocupacion = txtOcupacion.getText();
    String grupo = txtGrupo.getText().trim();
    
    String Idboleta = txtGrupo.getText().trim();

    // Validar campos obligatorios
    if (controlText.isEmpty() || nombre.isEmpty() || apellidoP.isEmpty() || apellidoM.isEmpty() || fecha == null ||
        telefono.isEmpty() || genero.isEmpty() || tutor.isEmpty() || correo.isEmpty() || ocupacion.isEmpty() || grupo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Mostrar cuadro de diálogo de confirmación
    int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea realizar estos cambios?", "Confirmar Cambios", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) {
        return; // Salir si el usuario no confirma
    }

    int selectedRow = tablaAlumno.getSelectedRow();
    if (selectedRow >= 0) {
        // Obtener el número de control del alumno seleccionado
        String numerocontrol = tablaAlumno.getValueAt(selectedRow, 0).toString();
        
        // Obtener el objeto Alumno a partir del número de control
        Alumno alumno = ControladorAlumno.getAlumno(numerocontrol);

        if (alumno != null) {
            // Actualizar los datos del alumno
            alumno.setNombre(nombre);
            alumno.setApellidoP(apellidoP);
            alumno.setApellidoM(apellidoM);
            alumno.setFechaNaci(fechaNacimiento);
            alumno.setGenero(genero);
            alumno.setTutor(tutor);
            alumno.setOcupacion(ocupacion);
            alumno.setTelefono(telefono);
            alumno.setCorreo(correo);
            alumno.setIdGrupo(grupo);
            
            

            // Actualizar el alumno en el controlador
            boolean actualizado = ControladorAlumno.actualizarAlumno(alumno);
            if (actualizado) {
                cargarDatos();
                Limpiar();
                JOptionPane.showMessageDialog(this, "Datos actualizados correctamente.");
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar los datos del alumno.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo encontrar el alumno para actualizar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        // Crear un nuevo alumno si no hay una fila seleccionada
        Alumno alumno = new Alumno(control, nombre, apellidoP, apellidoM, fechaNacimiento, genero, tutor, ocupacion, telefono, correo, grupo );
        boolean insertado = ControladorAlumno.insertarAlumno(alumno);
        if (insertado) {
            cargarDatos();
            Limpiar();
            JOptionPane.showMessageDialog(this, "Alumno guardado correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar el nuevo alumno.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}









public void cargarDatos() {
    
    List<Alumno> listaAlumnos = ControladorAlumno.obtenerAlumnos();
    DefaultTableModel modeloTabla = new DefaultTableModel(
    new String[]{"NumControl", "Nombre", "Apellido paterno", "Apellido materno", "Fecha de Nacimiento", "Género", "Tutor", "Ocupación", "Teléfono", "Correo", "Grupo"}, 0);

    modeloTabla.setRowCount(0);
       
        for (Alumno alumno : listaAlumnos) {
            modeloTabla.addRow (new  Object[]{
                alumno.getIdAlumno(),
                alumno.getNombre(),
                alumno.getApellidoP(),
                alumno.getApellidoM(),
                alumno.getFechaNaci(),
                alumno.getGenero(),
                alumno.getTutor(),
                alumno.getOcupacion(),    
                alumno.getTelefono(),
                alumno.getCorreo(),
                alumno.getIdGrupo()
                    
            });
        }
         tablaAlumno.setModel(modeloTabla);
    }

public void eliminarAlumno() {
    int selectedRow = tablaAlumno.getSelectedRow();
    if (selectedRow >= 0) {
        String control = tablaAlumno.getValueAt(selectedRow, 0).toString(); // Ajustar índice según tu tabla
        
        int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas eliminar este alumno?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            boolean eliminado = ControladorAlumno.eliminarAlumno(control);
            if (eliminado) {
                cargarDatos();
                JOptionPane.showMessageDialog(this, "Alumno eliminado correctamente.");
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar el alumno.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecciona un alumno para eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

public void cargarDatos2() {
    List<Alumno> listaAlumnos = ControladorAlumno.obtenerAlumnos();
    DefaultTableModel model = (DefaultTableModel) tablaAlumno.getModel();
    model.setRowCount(0); // Limpiar la tabla

    for (Alumno alumno : listaAlumnos) {
        Object[] row = new Object[11];
        
        row[0] = alumno.getIdAlumno();
        row[1] = alumno.getNombre();
        row[2] = alumno.getApellidoP();
        row[3] = alumno.getApellidoM();
        row[4] = alumno.getFechaNaci();
        row[5] = alumno.getGenero();
        row[6] = alumno.getTutor();
        row[7] = alumno.getOcupacion();
        row[8] = alumno.getTelefono();
        row[9] = alumno.getCorreo();
        row[10] = alumno.getIdGrupo();
        model.addRow(row);
    }
}


  public void rellenarDatos() {
    int selectedRow = tablaAlumno.getSelectedRow();
    if (selectedRow >= 0) {
        txtControl.setText(tablaAlumno.getValueAt(selectedRow, 0).toString());
        txtNombre.setText(tablaAlumno.getValueAt(selectedRow, 1).toString());
        txtApellidoP.setText(tablaAlumno.getValueAt(selectedRow, 2).toString());
        txtApellidoM.setText(tablaAlumno.getValueAt(selectedRow, 3).toString());
      
        try {
            String fechaNaci = tablaAlumno.getValueAt(selectedRow, 4).toString();
            Date fecha = new SimpleDateFormat("dd MMMM yyyy").parse(fechaNaci);
            calendario.setDate(fecha);
        } catch (ParseException e) {
            e.printStackTrace();
        }
        
        String genero = tablaAlumno.getValueAt(selectedRow, 5).toString();
        if (genero.equals("Masculino")) {
            btnMasculino.setSelected(true);
        } else {
            btnFemenino.setSelected(true);
        }

        txtTutor.setText(tablaAlumno.getValueAt(selectedRow, 6).toString());
        txtOcupacion.setText(tablaAlumno.getValueAt(selectedRow, 7).toString());
        txtNumeroTelefono.setText(tablaAlumno.getValueAt(selectedRow, 8).toString());
        txtCorreo.setText(tablaAlumno.getValueAt(selectedRow, 9).toString());
        txtGrupo.setText(tablaAlumno.getValueAt(selectedRow, 10).toString());
    }
  }

}
